#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Usage: curling [curl options]"
  exit 1
fi

echo "curl $@"
echo -e "NameLookup | Connect   | AppConnect | Pretransfer | Redirect | StartTransfer | TotalTime | ResponseCode"
echo "===========|===========|============|=============|==========|===============|===========|============="

while true; do
  http_response=$(curl -s -o /dev/null -w "%{time_namelookup}   | %{time_connect}  | %{time_appconnect}   | %{time_pretransfer}    | %{time_redirect} | %{time_starttransfer}      | %{time_total}  | %{http_code}\n" "$@")

  echo "$http_response"

  sleep 1
done
